// Generated by CoffeeScript 1.9.0

/*
 * Tests brobbot listeners
 */

(function() {
  module.exports = function(robot) {
    var assert;
    assert = require('assert');
    robot.hear(/static/i, function(msg) {
      return msg.http('http://127.0.0.1/test').get()(function(err, res, body) {
        return msg.send(body);
      });
    });
    robot.hear(/test/i, function(msg) {
      return msg.send("OK");
    });
    robot.hear(/reply/i, function(msg) {
      return msg.reply("OK");
    });
    robot.respond(/rsvp/i, function(msg) {
      return msg.send("responding");
    });
    robot.hear(/random/i, function(msg) {
      return msg.send(msg.random([1, 2]).toString());
    });
    return robot.catchAll(function(msg) {
      return msg.send('catch-all');
    });
  };

}).call(this);
