// Generated by CoffeeScript 1.9.0
(function() {
  var BrainSegment, _;

  _ = require('lodash');

  BrainSegment = (function() {
    function BrainSegment(brain, segmentName) {
      var obj, segmentRegex;
      if (segmentName == null) {
        segmentName = _.uniqueId();
      }
      obj = Object.create(brain);
      segmentRegex = new RegExp("^" + segmentName + ":");
      obj.key = function(key) {
        return brain.key(segmentName + ":" + key);
      };
      obj.unkey = function(key) {
        return brain.unkey(key).replace(segmentRegex, '');
      };
      return obj;
    }

    return BrainSegment;

  })();

  module.exports = BrainSegment;

}).call(this);
