// Generated by CoffeeScript 1.9.0
(function() {
  var Brain, BrainSegment, EventEmitter, Q, User, _,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __hasProp = {}.hasOwnProperty;

  EventEmitter = require('events').EventEmitter;

  User = require('./user');

  BrainSegment = require('./brain-segment');

  Q = require('q');

  _ = require('lodash');

  function iterValues(iter) {
    var result = [];
    for (var item of iter) {
      result.push(item);
    }
    return result;
  }

  Brain = (function(_super) {
    __extends(Brain, _super);

    function Brain(_at_robot) {
      this.robot = _at_robot;
      this._users = new Map();
      this._data = new Map();
      this.ready = Q(this);
    }

    Brain.prototype.reset = function() {
      this._users = new Map();
      this._data = new Map();
      return Q();
    };

    Brain.prototype.llen = function(key) {
      var list;
      list = this._data.get(this.key(key));
      if (list === void 0) {
        return Q(null);
      } else {
        return Q(list.length);
      }
    };

    Brain.prototype.lset = function(key, index, value) {
      var list;
      key = this.key(key);
      list = this._data.get(key);
      if (list === void 0) {
        list = [];
        this._data.set(key, list);
      }
      list[index] = this.serialize(value);
      return Q();
    };

    Brain.prototype.linsert = function(key, placement, pivot, value) {
      var index, list;
      key = this.key(key);
      list = this._data.get(key);
      if (list !== void 0) {
        pivot = this.serialize(pivot);
        index = _.findIndex(list, (function(_this) {
          return function(val) {
            return val === pivot;
          };
        })(this));
        if (index > -1) {
          if (placement === 'AFTER') {
            index = index + 1;
          }
          list.splice(index, 0, this.serialize(value));
        }
      }
      return Q();
    };

    Brain.prototype.lpush = function(key, value) {
      var list;
      key = this.key(key);
      list = this._data.get(key);
      if (list === void 0) {
        list = [];
        this._data.set(key, list);
      }
      list.unshift(this.serialize(value));
      return Q();
    };

    Brain.prototype.rpush = function(key, value) {
      var list;
      key = this.key(key);
      list = this._data.get(key);
      if (list === void 0) {
        list = [];
        this._data.set(key, list);
      }
      list.push(this.serialize(value));
      return Q();
    };

    Brain.prototype.lpop = function(key) {
      var _ref;
      return Q(this.deserialize((_ref = this._data.get(this.key(key))) != null ? _ref.shift() : void 0));
    };

    Brain.prototype.rpop = function(key) {
      var _ref;
      return Q(this.deserialize((_ref = this._data.get(this.key(key))) != null ? _ref.pop() : void 0));
    };

    Brain.prototype.lindex = function(key, index) {
      var _ref;
      return Q(this.deserialize(((_ref = this._data.get(this.key(key))) != null ? _ref[index] : void 0) || null));
    };

    Brain.prototype.lgetall = function(key) {
      return this.lrange(key, 0, -1);
    };

    Brain.prototype.lrange = function(key, start, end) {
      var list;
      list = this._data.get(this.key(key));
      if (list === void 0) {
        return Q(null);
      }
      if (end < 0) {
        end = list.length + end;
      }
      return Q(_.map(list.slice(start, end + 1), this.deserialize.bind(this)));
    };

    Brain.prototype.lrem = function(key, value) {
      var index, list;
      list = this._data.get(this.key(key));
      if (list) {
        index = _.findIndex(list, function(val) {
          return _.isEqual(val, value);
        });
        if (index > -1) {
          list.splice(index, 1);
        }
      }
      return Q();
    };

    Brain.prototype.sadd = function(key, value) {
      var set;
      key = this.key(key);
      set = this._data.get(key);
      if (set === void 0) {
        set = new Set();
        this._data.set(key, set);
      }
      set.add(this.serialize(value));
      return Q();
    };

    Brain.prototype.sismember = function(key, value) {
      var set;
      set = this._data.get(this.key(key));
      if (!set) {
        return Q(null);
      } else {
        return Q(set.has(this.serialize(value)));
      }
    };

    Brain.prototype.srem = function(key, value) {
      var set;
      set = this._data.get(this.key(key));
      if (set) {
        set["delete"](this.serialize(value));
      }
      return Q();
    };

    Brain.prototype.scard = function(key) {
      var set;
      set = this._data.get(this.key(key));
      if (set === void 0) {
        return Q(null);
      } else {
        return Q(set.size);
      }
    };

    Brain.prototype.spop = function(key) {
      var index, item, set;
      set = this._data.get(this.key(key));
      if (set === void 0) {
        return Q(null);
      }
      index = _.random(0, set.size - 1);
      item = iterValues(set.values())[index];
      set["delete"](item);
      return Q(this.deserialize(item));
    };

    Brain.prototype.srandmember = function(key) {
      var set;
      set = this._data.get(this.key(key));
      if (set === void 0 || set.size === 0) {
        return Q(null);
      }
      return Q(this.deserialize(iterValues(set.values())[_.random(0, set.size - 1)]));
    };

    Brain.prototype.smembers = function(key) {
      var _ref;
      return Q(((_ref = this._data.get(this.key(key))) != null ? iterValues(_ref.values()) : void 0) || null);
    };

    Brain.prototype.keys = function(searchKey) {
      if (searchKey == null) {
        searchKey = '';
      }
      searchKey = this.key(searchKey);
      return Q(_.map(_.filter(iterValues(this._data.keys()), function(key) {
        return key.indexOf(searchKey) === 0;
      }), this.unkey.bind(this)));
    };

    Brain.prototype.unkey = function(key) {
      return key;
    };

    Brain.prototype.key = function(key) {
      return key;
    };

    Brain.prototype.usersKey = function() {
      return 'users';
    };

    Brain.prototype.set = function(key, value) {
      this._data.set(this.key(key), this.serialize(value));
      return Q();
    };

    Brain.prototype.get = function(key) {
      var _ref;
      return Q(this.deserialize((_ref = this._data.get(this.key(key))) != null ? _ref : null));
    };

    Brain.prototype.type = function(key) {
      var val;
      val = this.deserialize(this._data.get(this.key(key)));
      if (val === void 0) {
        return null;
      } else if (val instanceof Map) {
        return 'hash';
      } else if (val instanceof Set) {
        return 'set';
      } else if (val instanceof Array) {
        return 'list';
      } else {
        return 'object';
      }
    };

    Brain.prototype.exists = function(key) {
      return Q(this._data.has(this.key(key)));
    };

    Brain.prototype.incrby = function(key, num) {
      key = this.key(key);
      this._data.set(key, (this._data.get(key) || 0) + num);
      return Q(this._data.get(key));
    };

    Brain.prototype.hkeys = function(table) {
      var hash = this._data.get(this.key(table));
      if (hash !== void 0) {
        return Q(iterValues(hash.keys()))
      }
      else {
        return Q(null);
      }
    };

    Brain.prototype.hvals = function(table) {
      var val;
      val = this._data.get(this.key(table));
      if (val === void 0) {
        return Q(null);
      } else {
        return Q(_.map(iterValues(val.values()), this.deserialize.bind(this)));
      }
    };

    Brain.prototype.hlen = function(table) {
      var val;
      val = this._data.get(this.key(table));
      if (val === void 0) {
        return Q(null);
      } else {
        return Q(val.size);
      }
    };

    Brain.prototype.hset = function(table, key, value) {
      var val;
      table = this.key(table);
      val = this._data.get(table);
      if (val === void 0) {
        val = new Map();
        this._data.set(table, val);
      }
      val.set(key, this.serialize(value));
      return Q();
    };

    Brain.prototype.hget = function(table, key) {
      var val;
      val = this._data.get(this.key(table));
      if (val === void 0) {
        return Q(null);
      } else {
        return Q(this.deserialize(val.get(key)));
      }
    };

    Brain.prototype.hdel = function(table, key) {
      var val;
      val = this._data.get(this.key(table));
      if (val !== void 0) {
        val["delete"](key);
      }
      return Q();
    };

    Brain.prototype.hgetall = function(table) {
      var _ref;
      return Q(new Map(((_ref = this._data.get(this.key(table))) != null ? _ref.entries() : void 0) || null));
    };

    Brain.prototype.hincrby = function(table, key, num) {
      var val;
      table = this.key(table);
      val = this._data.get(table);
      if (val === void 0) {
        val = new Map();
        this._data.set(table, val);
      }
      val.set(key, (val.get(key) || 0) + num);
      return Q(val.get(key));
    };

    Brain.prototype.remove = function(key) {
      this._data["delete"](this.key(key));
      return Q();
    };

    Brain.prototype.del = function(key) {
      return this.remove(key);
    };

    Brain.prototype.close = function() {
      return Q();
    };

    Brain.prototype.serialize = function(value) {
      return value;
    };

    Brain.prototype.deserialize = function(value) {
      return value;
    };

    Brain.prototype.users = function() {
      return Q(iterValues(this._users.values()));
    };

    Brain.prototype.addUser = function(user) {
      this._users.set(user.id, user);
      return Q(user);
    };

    Brain.prototype.userForId = function(id, options) {
      var user;
      user = this._users.get(id);
      if (user === void 0 || (options && options.room && (user.room !== options.room))) {
        return this.addUser(new User(id, options));
      }
      return Q(user);
    };

    Brain.prototype.userForName = function(name) {
      var lowerName, user;
      lowerName = name.toLowerCase();
      user = _.find(iterValues(this._users.values()), function(user) {
        return user.name && user.name.toString().toLowerCase() === lowerName;
      });
      return Q(user || null);
    };

    Brain.prototype.usersForRawFuzzyName = function(fuzzyName) {
      var lowerFuzzyName, users;
      lowerFuzzyName = fuzzyName.toLowerCase();
      users = _.filter(iterValues(this._users.values()), function(user) {
        return user.name.toLowerCase().lastIndexOf(lowerFuzzyName, 0) === 0;
      });
      return Q(users);
    };

    Brain.prototype.usersForFuzzyName = function(fuzzyName) {
      return this.usersForRawFuzzyName(fuzzyName).then(function(matchedUsers) {
        var lowerFuzzyName, user, _i, _len, _ref;
        lowerFuzzyName = fuzzyName.toLowerCase();
        for (_i = 0, _len = matchedUsers.length; _i < _len; _i++) {
          user = matchedUsers[_i];
          if (((_ref = user.name) != null ? _ref.toLowerCase() : void 0) === lowerFuzzyName) {
            return Q([user]);
          }
        }
        return Q(matchedUsers);
      });
    };

    Brain.prototype.segment = function(segment) {
      return new BrainSegment(this, segment);
    };

    return Brain;

  })(EventEmitter);

  module.exports = Brain;

}).call(this);
