// Generated by CoffeeScript 1.9.0
(function() {
  var RobotSegment, _;

  _ = require('lodash');

  RobotSegment = (function() {
    function RobotSegment(robot, segmentName) {
      var obj;
      if (segmentName == null) {
        segmentName = _.uniqueId();
      }
      obj = Object.create(robot);
      obj.brain = robot.brain.segment(segmentName);
      return obj;
    }

    return RobotSegment;

  })();

  module.exports = RobotSegment;

}).call(this);
