// Generated by CoffeeScript 1.9.0
(function() {
  var User;

  User = (function() {

    /*
     * Represents a participating user in the chat.
    #
     * id      - A unique ID for the user.
     * options - An optional Hash of key, value pairs for this user.
     */
    function User(_at_id, options) {
      var k;
      this.id = _at_id;
      if (options == null) {
        options = {};
      }
      for (k in options || {}) {
        this[k] = options[k];
      }
      this['name'] || (this['name'] = this.id.toString());
    }

    return User;

  })();

  module.exports = User;

}).call(this);
